version: "3.8"

services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json:rw
    networks:
      - web
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=talkcompiler@gmail.com"
      - "--certificatesresolvers.leresolver.acme.storage=/acme.json"

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nextjs-app
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.futurprive.com
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`futurprive.com`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=leresolver"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"
    depends_on:
      - django

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: django-app
    restart: always
    environment:
      - DEBUG=0
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=api.futurprive.com
      - DATABASE_ENGINE=django.db.backends.postgresql
      - DATABASE_NAME=futurprive
      - DATABASE_USER=futurpriveuser
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
    networks:
      - web
      - internal
    depends_on:
      - postgres
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`api.futurprive.com`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=leresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

  postgres:
    image: postgres:14-alpine
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=futurprive
      - POSTGRES_USER=futurpriveuser
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    networks:
      - internal

networks:
  web:
  internal:

volumes:
  postgres_data:
