services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json:rw
    networks:
      - web
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.leresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.leresolver.acme.email=talkcompiler@gmail.com"
      - "--certificatesresolvers.leresolver.acme.storage=/acme.json"

  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: nextjs-app
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://api.futurprive.com
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextjs.rule=Host(`futurprive.com`)"
      - "traefik.http.routers.nextjs.entrypoints=websecure"
      - "traefik.http.routers.nextjs.tls.certresolver=leresolver"
      - "traefik.http.services.nextjs.loadbalancer.server.port=3000"

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: django-app
    restart: always
    command: >
      sh -c "sleep 30 && python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=debug_secret_key
      - ALLOWED_HOSTS=*
      - DATABASE_ENGINE=django.db.backends.sqlite3
      - DATABASE_NAME=db.sqlite3
    networks:
      - web
    volumes:
      - ./backend:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`api.futurprive.com`)"
      - "traefik.http.routers.django.entrypoints=websecure"
      - "traefik.http.routers.django.tls.certresolver=leresolver"
      - "traefik.http.services.django.loadbalancer.server.port=8000"

networks:
  web:
