services:
  nextjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nextjs-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://django:8000
    command: pnpm dev
    depends_on:
      - django

  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-app
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=secret
      - ALLOWED_HOSTS=localhost,127.0.0.1,django
    restart: on-failure
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  node_modules: