# Global configuration
global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Entrypoints configuration
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

# Providers configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: web
  file:
    directory: "/etc/traefik/config"
    watch: true

# API and dashboard configuration
api:
  dashboard: true
  debug: false

# Certificate resolvers configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: "talkcompiler@gmail.com"
      storage: "/acme.json"
      httpChallenge:
        entryPoint: web

# Log configuration
log:
  level: "INFO"
  filePath: "/var/log/traefik/traefik.log"

accessLog:
  filePath: "/var/log/traefik/access.log"
